/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Notification {
  'userId' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'notificationId' : bigint,
}
export interface Order {
  'status' : OrderStatus,
  'recipeId' : bigint,
  'userId' : Principal,
  'orderId' : bigint,
  'timestamp' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Recipe {
  'title' : string,
  'recipeId' : bigint,
  'authorId' : Principal,
  'cookTime' : bigint,
  'description' : string,
  'instructions' : Array<string>,
  'imageUrl' : string,
  'category' : string,
  'rating' : bigint,
  'servings' : bigint,
  'ingredients' : Array<string>,
}
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNotification' : ActorMethod<[Principal, string], bigint>,
  'createRecipe' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      Array<string>,
      string,
      bigint,
      bigint,
      string,
    ],
    bigint
  >,
  'deleteRecipe' : ActorMethod<[bigint], undefined>,
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getRecipe' : ActorMethod<[bigint], [] | [Recipe]>,
  'getRecipesByAuthor' : ActorMethod<[Principal], Array<Recipe>>,
  'getUserNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'placeOrder' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateRecipe' : ActorMethod<
    [
      bigint,
      string,
      string,
      Array<string>,
      Array<string>,
      string,
      bigint,
      bigint,
      string,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];