/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Recipe = IDL.Record({
  'title' : IDL.Text,
  'recipeId' : IDL.Nat,
  'authorId' : IDL.Principal,
  'cookTime' : IDL.Nat,
  'description' : IDL.Text,
  'instructions' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Nat,
  'servings' : IDL.Nat,
  'ingredients' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'recipeId' : IDL.Nat,
  'userId' : IDL.Principal,
  'orderId' : IDL.Nat,
  'timestamp' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Notification = IDL.Record({
  'userId' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat,
  'notificationId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNotification' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'createRecipe' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteRecipe' : IDL.Func([IDL.Nat], [], []),
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getRecipe' : IDL.Func([IDL.Nat], [IDL.Opt(Recipe)], ['query']),
  'getRecipesByAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Recipe)],
      ['query'],
    ),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateRecipe' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Recipe = IDL.Record({
    'title' : IDL.Text,
    'recipeId' : IDL.Nat,
    'authorId' : IDL.Principal,
    'cookTime' : IDL.Nat,
    'description' : IDL.Text,
    'instructions' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Nat,
    'servings' : IDL.Nat,
    'ingredients' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'recipeId' : IDL.Nat,
    'userId' : IDL.Principal,
    'orderId' : IDL.Nat,
    'timestamp' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Notification = IDL.Record({
    'userId' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
    'notificationId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNotification' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'createRecipe' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteRecipe' : IDL.Func([IDL.Nat], [], []),
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getRecipe' : IDL.Func([IDL.Nat], [IDL.Opt(Recipe)], ['query']),
    'getRecipesByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Recipe)],
        ['query'],
      ),
    'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateRecipe' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };